# Generated by Django 4.2.6 on 2025-02-25 10:35

from django.db import migrations, models
import site_cmds.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=5000)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoûtDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cobalt_intersite_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('cobalt_transfert_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('cuivre_intersite_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('cuivre_transfert_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('unit_price_intersite', models.DecimalField(decimal_places=0, default=350, editable=False, max_digits=10)),
                ('unit_price_transfert', models.DecimalField(decimal_places=0, default=1000, editable=False, max_digits=10)),
                ('total_price_intersite', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15)),
                ('total_price_transfert', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15)),
                ('number_of_intersite_items', models.PositiveIntegerField(default=0, editable=False)),
                ('number_of_transfert_items', models.PositiveIntegerField(default=0, editable=False)),
                ('total_number_of_items', models.PositiveIntegerField(default=0, editable=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='DecaissementReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('numero_reference', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('tresorier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cobalt_intersite_existant', models.PositiveIntegerField(default=0)),
                ('cobalt_transfert_existant', models.PositiveIntegerField(default=0)),
                ('cuivre_intersite_existant', models.PositiveIntegerField(default=0)),
                ('cuivre_transfert_existant', models.PositiveIntegerField(default=0)),
                ('cobalt_intersite_recu', models.PositiveIntegerField(default=0)),
                ('cobalt_transfert_recu', models.PositiveIntegerField(default=0)),
                ('cuivre_intersite_recu', models.PositiveIntegerField(default=0)),
                ('cuivre_transfert_recu', models.PositiveIntegerField(default=0)),
                ('cobalt_intersite_sorti', models.PositiveIntegerField(default=0)),
                ('cobalt_transfert_sorti', models.PositiveIntegerField(default=0)),
                ('cuivre_intersite_sorti', models.PositiveIntegerField(default=0)),
                ('cuivre_transfert_sorti', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Décaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tresorier', models.CharField(choices=[('KASONGO', 'Kasongo'), ('TSHITSHI', 'Tshitshi')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('motif', models.CharField(default='Motif inconnu', max_length=1000)),
                ('amount_usd', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('amount_cdf', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entrée',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doc_chinois_usd', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('div_chinois_cdf', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('doc_congolais_usd', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('div_congolais_cdf', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('frais_de_depot_cdf', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='Dld/', validators=[site_cmds.models.validate_file_extension])),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
